CREATE TABLE `images` (
  `PICID` int(11) NOT NULL,
  `USERID` int(11) NOT NULL,
  `PATH` varchar(255) DEFAULT NULL,
  `TEMP_PATH` varchar(255) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE `post` (
  `POSTID` int(11) NOT NULL,
  `DATE` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `USERID` int(11) NOT NULL,
  `TITLE` varchar(200) NOT NULL,
  `CONTENT` mediumtext NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf16;

CREATE TABLE `user` (
  `USERID` int(11) NOT NULL,
  `USERNAME` varchar(20) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  `PASSWORD` varchar(255) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  `EMAIL` varchar(100) CHARACTER SET ascii COLLATE ascii_bin DEFAULT NULL,
  `REGISTERED` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `LASTSEEN` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `LASTCHANGED` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `IDENTIFIER` varchar(255) NOT NULL,
  `TOKEN` varchar(255) NOT NULL,
  `ROLE` varchar(255) DEFAULT NULL,
  `VISIBILITY` varchar(30) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf16;

ALTER TABLE `images`
  ADD PRIMARY KEY (`PICID`);

ALTER TABLE `post`
  ADD PRIMARY KEY (`POSTID`);

ALTER TABLE `user`
  ADD PRIMARY KEY (`USERID`);

ALTER TABLE `images`
  MODIFY `PICID` int(11) NOT NULL AUTO_INCREMENT;

ALTER TABLE `post`
  MODIFY `POSTID` int(11) NOT NULL AUTO_INCREMENT;

ALTER TABLE `user`
  MODIFY `USERID` int(11) NOT NULL AUTO_INCREMENT;
COMMIT;
