SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET AUTOCOMMIT = 0;
START TRANSACTION;
SET time_zone = "+00:00";

--
-- Database: `jaseph`
--

-- --------------------------------------------------------

CREATE TABLE `draft` (
  `DRAFTID` int(11) NOT NULL,
  `USERID` int(11) NOT NULL,
  `TITLE` varchar(200) NOT NULL,
  `CONTENT` mediumtext NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf16;

CREATE TABLE `images` (
  `PICID` int(11) NOT NULL,
  `USERID` int(11) NOT NULL,
  `PATH` varchar(255) DEFAULT NULL,
  `TEMP_PATH` varchar(255) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE `post` (
  `POSTID` int(11) NOT NULL,
  `DATE` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `USERID` int(11) NOT NULL,
  `TITLE` varchar(200) NOT NULL,
  `CONTENT` mediumtext NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf16;

CREATE TABLE `saved` (
  `USERID` int(11) NOT NULL,
  `POSTID` int(11) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf16;

CREATE TABLE `user` (
  `USERID` int(11) NOT NULL,
  `USERNAME` varchar(20) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  `PASSWORD` varchar(255) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  `REGISTERED` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `LASTSEEN` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `LASTCHANGED` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `IDENTIFIER` varchar(255) DEFAULT NULL,
  `ROLE` varchar(255) NOT NULL DEFAULT 'COMMON',
  `VISIBILITY` varchar(30) NOT NULL DEFAULT 'VISIBLE'
) ENGINE=InnoDB DEFAULT CHARSET=utf16;

--
-- PRIMARY KEYS
--

ALTER TABLE `draft`
  ADD PRIMARY KEY (`DRAFTID`);

ALTER TABLE `images`
  ADD PRIMARY KEY (`PICID`);

ALTER TABLE `post`
  ADD PRIMARY KEY (`POSTID`);

ALTER TABLE `user`
  ADD PRIMARY KEY (`USERID`);

--
-- AUTO_INCREMENT
--

ALTER TABLE `draft`
  MODIFY `DRAFTID` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=1;

ALTER TABLE `images`
  MODIFY `PICID` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=1;

ALTER TABLE `post`
  MODIFY `POSTID` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=1;

ALTER TABLE `user`
  MODIFY `USERID` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=1;
COMMIT;
